####################################################################
# This file is automatically generated by the SphinxSearch Plugin
#
#  WARNING: YOUR DATABASE PASSWORD/USERNAME ARE CONTAINED IN THIS FILE!!!!
#
# -@author mcuhq
####################################################################


#create an offset from the `{ss_prefix}discussion`
#notice this: 0 as title ...this is key to not select dups

source {ss_prefix}main_comment
{
    type            = mysql
    sql_host        = {sql_host}
    sql_user        = {sql_user}
    sql_pass        = {sql_pass}
    sql_db          = {sql_db}
    {sql_sock}
    sql_port        = 3306    #optional, default is 3306

    sql_query_pre   = SET NAMES utf8
    sql_query_pre   = REPLACE INTO {db_prefix}sph_counter SELECT 1, MAX(c.CommentID +1) FROM {db_prefix}Comment as c
    sql_query       = SELECT (c.CommentID +1 + (SELECT MAX(d.DiscussionID) FROM {db_prefix}Discussion as d)), c.CommentID as docid, 1 as isComment,\
            c.Body as body, UNIX_TIMESTAMP(c.DateInserted) as docdateinserted,\
\
            0 as title, d.CountComments as CountComments, d.CountViews as CountViews,\
\
			cat.CategoryID as catid, cat.PermissionCategoryID as catpermid,\
\
            u.Name as user, u.UserID as UserID\
\
            FROM {db_prefix}Comment as c\
\
            INNER JOIN {db_prefix}Discussion as d ON c.DiscussionID = d.DiscussionID\
            INNER JOIN {db_prefix}User as u ON c.InsertUserID = u.UserID\
	    INNER JOIN {db_prefix}Category as cat ON d.CategoryID = cat.CategoryID\
\
            WHERE (c.CommentID +1) <=( SELECT max_doc_id FROM {db_prefix}sph_counter WHERE counter_id=1 )\

	sql_field_string = user #don't require sql call to get username when filtring by user on the main search page

	sql_attr_uint = UserID
	sql_attr_uint = docid
	sql_attr_uint = catid
        sql_attr_bigint = catpermid #so results respect user permissions (must be signed!)

        {tag_attr}

	sql_attr_timestamp = docdateinserted
    sql_attr_uint = CountViews
    sql_attr_uint = CountComments
    sql_attr_uint = isComment        			#distinguishes between a discussion/comment


}

source {ss_prefix}delta_comment : {ss_prefix}main_comment
{

    sql_query_pre = SET NAMES utf8

    sql_query   = SELECT  (c.CommentID +1 + (SELECT MAX(d.DiscussionID) FROM {db_prefix}Discussion as d)), c.CommentID as docid, 1 as isComment,\
            c.Body as body, UNIX_TIMESTAMP(c.DateInserted) as docdateinserted,\
\
            0 as title, d.CountComments as CountComments, d.CountViews as CountViews,\
\
			cat.CategoryID as catid, cat.PermissionCategoryID as catpermid,\
\
            u.Name as user, u.UserID as UserID\
\
            FROM {db_prefix}Comment as c\
\
            INNER JOIN {db_prefix}Discussion as d ON c.DiscussionID = d.DiscussionID\
            INNER JOIN {db_prefix}User as u ON c.InsertUserID = u.UserID\
            INNER JOIN {db_prefix}Category as cat ON d.CategoryID = cat.CategoryID\
\
            WHERE (c.CommentID +1) > (SELECT max_doc_id FROM {db_prefix}sph_counter WHERE counter_id=1)\

}

#this source selects the discussion body  and its related info, exactly like the `{ss_prefix}comments` does.
#the discussion body is refered to as a comment to fit with the rest of the naming scheme
#yes, there are duplicate attributes stored, but the two sources MUST match columns(see MYSQL UNION)


source {ss_prefix}main_discussion
{
    type            = mysql
    sql_host        = {sql_host}
    sql_user        = {sql_user}
    sql_pass        = {sql_pass}
    sql_db          = {sql_db}
    {sql_sock}
    sql_port        = 3306    #optional, default is 3306

    sql_query_pre   = SET NAMES utf8
    sql_query_pre   = REPLACE INTO {db_prefix}sph_counter SELECT 2, MAX(d.DiscussionID) FROM {db_prefix}Discussion as d
    sql_query       = SELECT  d.DiscussionID, d.DiscussionID as docid, 0 as isComment,\
            d.Body as body, UNIX_TIMESTAMP(d.DateInserted) as docdateinserted,\
\
            d.Name as title, d.CountComments as CountComments, d.CountViews as CountViews,\
\
			d.CategoryID as catid, cat.PermissionCategoryID as catpermid,\
\
            u.Name as user, u.UserID as UserID\
\
            FROM {db_prefix}Discussion as d\
\
            INNER JOIN {db_prefix}Category as cat ON d.CategoryID = cat.CategoryID\
            INNER  JOIN {db_prefix}User as u ON d.InsertUserID = u.UserID \
\
            WHERE (d.DiscussionID) <= (SELECT max_doc_id FROM {db_prefix}sph_counter WHERE counter_id=2)\

	sql_field_string = user #don't require sql call to get username when filtring by user on the main search page

	sql_attr_uint = UserID
	sql_attr_uint = docid
	sql_attr_uint = catid
        sql_attr_bigint = catpermid #so results respect user permissions (must be signed!)

        {tag_attr}

	sql_attr_timestamp = docdateinserted
    sql_attr_uint = CountViews
    sql_attr_uint = CountComments
    sql_attr_uint = isComment        			#distinguishes between a discussion/comment

}


source {ss_prefix}delta_discussion : {ss_prefix}main_discussion
{
    sql_query_pre = SET NAMES utf8
    sql_query = SELECT  d.DiscussionID, d.DiscussionID as docid, 0 as isComment,\
                         d.Body as body, UNIX_TIMESTAMP(d.DateInserted) as docdateinserted,\
\
            d.Name as title, d.CountComments as CountComments, d.CountViews as CountViews,\
\
			d.CategoryID as catid, cat.PermissionCategoryID as catpermid,\
\
            u.Name as user, u.UserID as UserID\
\
            FROM {db_prefix}Discussion as d\
\
            INNER JOIN {db_prefix}Category as cat ON d.CategoryID = cat.CategoryID\
            INNER  JOIN {db_prefix}User as u ON d.InsertUserID = u.UserID \
\
			WHERE (d.DiscussionID) > (SELECT max_doc_id FROM {db_prefix}sph_counter WHERE counter_id=2)\

}

index {ss_prefix}main
{
    source          = {ss_prefix}main_comment
    source          = {ss_prefix}main_discussion
    path            = {data_path}{ss_prefix}main
    docinfo         = extern
    charset_type    = {charset_type} #For more charsets, for Arabic, Persian, Italian, etc forums, please see: http://sphinxsearch.com/wiki/doku.php?id=charset_tables
}
index {ss_prefix}delta : {ss_prefix}main
{
    source          = {ss_prefix}delta_comment
    source          = {ss_prefix}delta_discussion
    path            = {data_path}{ss_prefix}delta
}

source {ss_prefix}stats
{
	type        = mysql
    sql_host        = {sql_host}
    sql_user        = {sql_user}
    sql_pass        = {sql_pass}
    sql_db          = {sql_db}
    {sql_sock}
    sql_port        = 3306    #optional, default is 3306

	sql_query_pre	= SET NAMES utf8
	sql_query	=  select id, keywords as keywords, crc32(keywords) as keywords_crc, mode,\
    UNIX_TIMESTAMP(date_added) as date_added \
    from {db_prefix}sph_stats;

    sql_attr_uint		= mode
    sql_attr_uint       = keywords_crc
    sql_attr_timestamp	= date_added
}

index {ss_prefix}stats
{
	source	= {ss_prefix}stats
	path	= {data_path}{ss_prefix}stats
	docinfo	= extern


}

index vanilla
{
    type            =  distributed
    local           =  {ss_prefix}main
    local           =  {ss_prefix}delta


    #index settings
    morphology      = {morphology}
    dict            = {dict}
    min_stemming_len = {min_stemming_len}
    stopwords       = {stopwords} #path to text file if enabled, else empty
    wordforms       = {wordforms}
    min_word_len    = {min_word_len}
    min_prefix_len  = {min_prefix_len}
    min_infix_len   = {min_infix_len}
    enable_star     = {enable_star}
    ngram_len       = {ngram_len}
    html_strip      = {html_strip}
    ondisk_dict     = {ondisk_dict}
    inplace_enable  = {inplace_enable}
    expand_keywords = {expand_keywords}
    rt_mem_limit    = {rt_mem_limit}
    # 'utf-8' defaults for English and Russian
    charset_table = 0..9, A..Z->a..z, _, a..z, \
                    U+410..U+42F->U+430..U+44F, U+430..U+44F


}

indexer
{
    #indexer settings
    mem_limit       = {mem_limit}
    max_iops        = {max_iops}
    max_iosize      = {max_iosize}
    write_buffer    = {write_buffer}
    max_file_field_buffer = {max_file_field_buffer}
}

searchd
{
    port            = {searchd_port}
    log             = {log_path}
    query_log       = {query_path}
    pid_file        = {PID_path}


    #settings
    read_timeout    = {read_timeout}
    client_timeout  = {client_timeout}
    max_children    = {max_children}
    max_matches     = {max_matches}
    read_buffer     = {read_buffer}
    workers         = {workers}
    thread_stack    = {thread_stack}
    expansion_limit = {expansion_limit}
    prefork_rotation_throttle = {prefork_rotation_throttle}

    compat_sphinxql_magics = 0 # the future is now
}

# --eof--